version: "3"

services:
  stickertrade:
    image: ghcr.io/fogo-sh/stickertrade:latest
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./data:/app/data"
    environment:
      - DATABASE_URL=file:../data/docker.db

  minio:
    image: minio/minio:RELEASE.2022-10-29T06-21-33Z
    command: server --console-address ":9001" /data/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
