version: "3"

services:
  stickertrade:
    image: "stickertrade"
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./data:/app/data"
    environment:
      - DATABASE_URL=file:../data/docker.db