version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db:
