# fly.toml file generated for stickertrade on 2021-10-22T22:45:00-02:30

app = "stickertrade"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[deploy]
  release_command = "/app/bin/stickertrade eval Stickertrade.Release.migrate"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s" # allow some time for startup
    interval = "15s"
    restart_limit = 6
    timeout = "2s"